package com.autospec.dto;

import com.autospec.entity.ModelInvocation;

import java.math.BigDecimal;

public record ModelInvocationResponse(
        Long id,
        Long taskId,
        Long workflowRunId,
        Long workflowNodeRunId,
        String callId,
        String callType,
        String executionId,
        Integer callSequence,
        Integer attempt,
        String correlationId,
        Long promptVersionId,
        String promptKey,
        String promptVersion,
        String promptChecksum,
        String schemaVersion,
        String contractHash,
        String providerKey,
        String modelName,
        String routeKey,
        String routeReason,
        Boolean fallbackUsed,
        String contextManifestJson,
        String agentNode,
        String status,
        Integer durationMs,
        Integer inputTokens,
        Integer outputTokens,
        Integer cacheTokens,
        Integer callCount,
        BigDecimal estimatedCost,
        Integer reservedInputTokens,
        Integer reservedOutputTokens,
        BigDecimal reservedCost,
        Integer settlementDeltaTokens,
        BigDecimal settlementDeltaCost,
        String normalizedParamsHash,
        String resultHash,
        String errorCode,
        Long deadlineEpochMs,
        String idempotencyKey,
        String toolName,
        String toolVersion,
        String permissionPolicy,
        String referenceSourcesJson,
        String redactedParamsJson,
        BigDecimal score,
        String errorMessage
) {

    public static ModelInvocationResponse from(ModelInvocation invocation) {
        return new ModelInvocationResponse(
                invocation.getId(),
                invocation.getTaskId(),
                invocation.getWorkflowRunId(),
                invocation.getWorkflowNodeRunId(),
                invocation.getCallId(),
                invocation.getCallType(),
                invocation.getExecutionId(),
                invocation.getCallSequence(),
                invocation.getAttempt(),
                invocation.getCorrelationId(),
                invocation.getPromptVersionId(),
                invocation.getPromptKey(),
                invocation.getPromptVersion(),
                invocation.getPromptChecksum(),
                invocation.getSchemaVersion(),
                invocation.getContractHash(),
                invocation.getProviderKey(),
                invocation.getModelName(),
                invocation.getRouteKey(),
                invocation.getRouteReason(),
                invocation.getFallbackUsed(),
                invocation.getContextManifestJson(),
                invocation.getAgentNode(),
                invocation.getStatus(),
                invocation.getDurationMs(),
                invocation.getInputTokens(),
                invocation.getOutputTokens(),
                invocation.getCacheTokens(),
                invocation.getCallCount(),
                invocation.getEstimatedCost(),
                invocation.getReservedInputTokens(),
                invocation.getReservedOutputTokens(),
                invocation.getReservedCost(),
                invocation.getSettlementDeltaTokens(),
                invocation.getSettlementDeltaCost(),
                invocation.getNormalizedParamsHash(),
                invocation.getResultHash(),
                invocation.getErrorCode(),
                invocation.getDeadlineEpochMs(),
                invocation.getIdempotencyKey(),
                invocation.getToolName(),
                invocation.getToolVersion(),
                invocation.getPermissionPolicy(),
                invocation.getReferenceSourcesJson(),
                invocation.getRedactedParamsJson(),
                invocation.getScore(),
                invocation.getErrorMessage()
        );
    }
}
