package com.autospec.dto;

import com.autospec.entity.WorkflowNodeRun;

import java.math.BigDecimal;
import java.time.LocalDateTime;

public record WorkflowNodeRunResponse(
        Long id,
        Long workflowRunId,
        String nodeId,
        Integer revision,
        Integer attempt,
        String executionId,
        String contractHash,
        String executionBundleHash,
        Long fencingToken,
        String status,
        String handlerKey,
        String handlerVersion,
        Integer timeoutMs,
        Integer durationMs,
        String budgetReservationId,
        Long reservedInputTokens,
        Long reservedOutputTokens,
        BigDecimal reservedCost,
        Integer reservedModelCalls,
        Integer actualInputTokens,
        Integer actualOutputTokens,
        Integer actualCacheTokens,
        BigDecimal actualCost,
        Integer actualModelCalls,
        Integer actualToolCalls,
        String budgetStatus,
        LocalDateTime budgetSettledAt,
        String inputJson,
        String outputJson,
        String errorCode,
        String errorMessage,
        LocalDateTime queuedAt,
        LocalDateTime startedAt,
        LocalDateTime heartbeatAt,
        LocalDateTime finishedAt,
        String workerId
) {
    public static WorkflowNodeRunResponse from(WorkflowNodeRun run) {
        return new WorkflowNodeRunResponse(
                run.getId(),
                run.getWorkflowRunId(),
                run.getNodeId(),
                run.getRevision(),
                run.getAttempt(),
                run.getExecutionId(),
                run.getContractHash(),
                run.getExecutionBundleHash(),
                run.getFencingToken(),
                run.getStatus(),
                run.getHandlerKey(),
                run.getHandlerVersion(),
                run.getTimeoutMs(),
                run.getDurationMs(),
                run.getBudgetReservationId(),
                run.getReservedInputTokens(),
                run.getReservedOutputTokens(),
                run.getReservedCost(),
                run.getReservedModelCalls(),
                run.getActualInputTokens(),
                run.getActualOutputTokens(),
                run.getActualCacheTokens(),
                run.getActualCost(),
                run.getActualModelCalls(),
                run.getActualToolCalls(),
                run.getBudgetStatus(),
                run.getBudgetSettledAt(),
                run.getInputJson(),
                run.getOutputJson(),
                run.getErrorCode(),
                run.getErrorMessage(),
                run.getQueuedAt(),
                run.getStartedAt(),
                run.getHeartbeatAt(),
                run.getFinishedAt(),
                run.getWorkerId()
        );
    }
}
