create table if not exists workflow_tool_call_fact (
    id bigint primary key auto_increment,
    request_id varchar(255) not null,
    idempotency_key varchar(255) not null,
    execution_id varchar(255) not null,
    workflow_run_id bigint not null,
    node_run_id bigint not null,
    node_id varchar(128) not null,
    actor_user_id bigint not null,
    project_id bigint not null,
    fencing_token bigint not null,
    deadline_epoch_ms bigint not null,
    execution_bundle_hash varchar(64) null,
    policy_hash varchar(64) not null,
    name varchar(128) not null,
    version varchar(64) not null,
    normalized_params_hash varchar(64) not null,
    status varchar(16) not null,
    result_json longtext null,
    result_hash varchar(64) null,
    error_code varchar(128) null,
    error_message varchar(1000) null,
    cached boolean not null default false,
    source_execution_id varchar(255) null,
    attempts int not null default 1,
    duration_ms int not null default 0,
    correlation_id varchar(128) null,
    traceparent varchar(255) null,
    tracestate varchar(512) null,
    created_at timestamp not null default current_timestamp,
    constraint uk_workflow_tool_call_request unique (request_id),
    constraint uk_workflow_tool_call_idempotency unique (idempotency_key),
    index idx_workflow_tool_call_execution (execution_id, created_at),
    index idx_workflow_tool_call_project (project_id, created_at),
    index idx_workflow_tool_call_status (status, created_at)
);
