create table if not exists workflow_agent_step_fact (
    id bigint primary key auto_increment,
    workflow_run_id bigint not null,
    node_run_id bigint not null,
    node_id varchar(128) not null,
    revision int not null,
    attempt int not null,
    execution_id varchar(255) not null,
    contract_hash varchar(64) null,
    step int not null,
    phase varchar(64) not null,
    status varchar(32) not null,
    reason_code varchar(128) null,
    plan_hash varchar(64) null,
    observation_hash varchar(64) null,
    validation_issue_codes_json longtext null,
    model_call_ref varchar(255) null,
    tool_call_ref varchar(255) null,
    started_at_epoch_ms bigint null,
    finished_at_epoch_ms bigint null,
    duration_ms int null,
    created_at timestamp not null default current_timestamp,
    constraint uk_workflow_agent_step_execution unique (execution_id, step),
    index idx_workflow_agent_step_run (workflow_run_id, node_run_id, step),
    index idx_workflow_agent_step_node (node_id, created_at)
);
