from __future__ import annotations

import hashlib
import json
import re
from dataclasses import dataclass
from typing import Any

from schemas.spec_contract import (
    SpecApi,
    SpecContract,
    SpecField,
    SpecFieldType,
    SpecTable,
    normalise_spec_contract,
)


COMPILER_VERSION = "spec-compiler-v1"


@dataclass(frozen=True)
class CompiledSpec:
    files: dict[str, str]
    source_digest: str
    manifest: dict[str, Any]


def compile_spec(spec: SpecContract | dict[str, Any]) -> CompiledSpec:
    contract = normalise_spec_contract(spec)
    canonical = _canonical(contract.model_dump(mode="json"))
    source_digest = hashlib.sha256(canonical.encode("utf-8")).hexdigest()
    files = {
        "openapi.json": _openapi(contract),
        "schema.sql": _schema_sql(contract),
        "client.ts": _client_ts(contract),
        "bindings.ts": _bindings_ts(contract),
        "tsconfig.json": _tsconfig(),
    }
    manifest = {
        "schema_version": "compiled-spec-manifest-v1",
        "compiler_version": COMPILER_VERSION,
        "contract_id": contract.contract_id,
        "source_digest": source_digest,
        "files": {
            name: hashlib.sha256(content.encode("utf-8")).hexdigest()
            for name, content in sorted(files.items())
        },
    }
    files = {**files, "manifest.json": _canonical(manifest)}
    return CompiledSpec(files=files, source_digest=source_digest, manifest=manifest)


def _openapi(spec: SpecContract) -> str:
    paths: dict[str, Any] = {}
    for api in sorted(spec.apis, key=lambda item: (item.path, item.method, item.api_id)):
        success_status = str(getattr(api, "success_status", 200))
        operation: dict[str, Any] = {
            "operationId": api.api_id,
            "responses": {
                success_status: {
                    "description": "Successful response",
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    field.name: _openapi_type(field.type)
                                    for field in api.responses
                                },
                                "required": [field.name for field in api.responses if not field.nullable],
                            },
                        }
                    },
                }
            },
        }
        parameters = []
        body_fields = []
        for parameter in sorted(api.parameters, key=lambda item: (item.location, item.name)):
            if parameter.location == "body":
                body_fields.append(parameter)
            else:
                parameters.append({
                    "name": parameter.name,
                    "in": parameter.location,
                    "required": parameter.required or parameter.location == "path",
                    "schema": _openapi_type(parameter.type),
                })
        if parameters:
            operation["parameters"] = parameters
        if body_fields:
            operation["requestBody"] = {
                "required": any(item.required for item in body_fields),
                "content": {"application/json": {"schema": {
                    "type": "object",
                    "properties": {item.name: _openapi_type(item.type) for item in body_fields},
                    "required": [item.name for item in body_fields if item.required],
                }}},
            }
        if api.auth_required:
            operation["security"] = [{"AutoSpecBearer": []}]
        paths.setdefault(api.path, {})[api.method.lower()] = operation
    document = {
        "openapi": "3.1.0",
        "info": {"title": spec.contract_id, "version": "1.0.0"},
        "paths": paths,
        "components": {"securitySchemes": {"AutoSpecBearer": {"type": "http", "scheme": "bearer"}}},
    }
    return _canonical(document)


def _schema_sql(spec: SpecContract) -> str:
    chunks: list[str] = ["-- generated by spec-compiler-v1", "SET NAMES utf8mb4;"]
    for table in sorted(spec.tables, key=lambda item: item.name):
        columns = []
        for field in table.fields:
            column = f"  `{field.name}` {_sql_type(field.type)}"
            if not field.nullable:
                column += " NOT NULL"
            if field.unique:
                column += " UNIQUE"
            if field.default is not None:
                column += f" DEFAULT {_sql_literal(field.default)}"
            columns.append(column)
        primary_keys = [field.name for field in table.fields if field.primary_key]
        if primary_keys:
            columns.append("  PRIMARY KEY (" + ", ".join(f"`{name}`" for name in primary_keys) + ")")
        chunks.append(
            f"CREATE TABLE `{table.name}` (\n" + ",\n".join(columns) + "\n) ENGINE=InnoDB;"
        )
    for table in sorted(spec.tables, key=lambda item: item.name):
        for field in table.fields:
            if field.foreign_key is None:
                continue
            chunks.append(
                f"ALTER TABLE `{table.name}` ADD CONSTRAINT `fk_{table.name}_{field.name}` "
                f"FOREIGN KEY (`{field.name}`) REFERENCES `{field.foreign_key.table}` (`{field.foreign_key.field}`);"
            )
    return "\n\n".join(chunks) + "\n"


def _client_ts(spec: SpecContract) -> str:
    lines = [
        "/* generated by spec-compiler-v1 */",
        "export type Json = string | number | boolean | null | Json[] | { [key: string]: Json };",
        "export type RequestOptions = RequestInit & { baseUrl?: string };",
        "",
        "async function request<T>(path: string, options: RequestOptions = {}): Promise<T> {",
        "  const response = await fetch(`${options.baseUrl ?? ''}${path}`, options);",
        "  if (!response.ok) throw new Error(`HTTP ${response.status}`);",
        "  return response.json() as Promise<T>;",
        "}",
        "",
    ]
    for api in sorted(spec.apis, key=lambda item: item.api_id):
        args = ", ".join(
            f"{parameter.name}: {_ts_type(parameter.type)}"
            for parameter in api.parameters
            if parameter.location == "body"
        )
        ts_api_name = _ts_identifier(api.api_id)
        response_type = f"{ts_api_name}Response"
        lines.extend([
            f"export type {response_type} = {{",
            *[f"  {field.name}{'?' if field.nullable else ''}: {_ts_type(field.type)};" for field in api.responses],
            "};",
            f"export async function {ts_api_name}({args}{', ' if args else ''}options: RequestOptions = {{}}): Promise<{response_type}> {{",
            f"  return request<{response_type}>('{api.path}', {{ ...options, method: '{api.method}' }});",
            "}",
            "",
        ])
    return "\n".join(lines)


def _bindings_ts(spec: SpecContract) -> str:
    lines = ["/* generated by spec-compiler-v1 */", "export const frontendBindings = {"]
    for binding in sorted(spec.frontend_bindings, key=lambda item: item.binding_id):
        lines.append(
            f"  '{binding.binding_id}': {{ component: '{binding.component}', apiId: '{binding.api_id}', method: '{binding.method}', path: '{binding.path}' }},"
        )
    lines.extend(["} as const;", ""])
    return "\n".join(lines)


def _tsconfig() -> str:
    return _canonical({
        "compilerOptions": {
            "target": "ES2022",
            "module": "ESNext",
            "moduleResolution": "Bundler",
            "strict": True,
            "noEmit": True,
            "noImplicitAny": True,
            "noUncheckedIndexedAccess": True,
            "skipLibCheck": False,
            "lib": ["ES2022", "DOM"],
        },
        "files": ["client.ts", "bindings.ts"],
    })


def _openapi_type(field_type: SpecFieldType) -> dict[str, Any]:
    mapping = {"string": "string", "integer": "integer", "bigint": "integer", "decimal": "number", "boolean": "boolean", "date": "string", "datetime": "string", "json": "object"}
    result: dict[str, Any] = {"type": mapping[field_type.kind]}
    if field_type.kind in {"date", "datetime"}:
        result["format"] = "date" if field_type.kind == "date" else "date-time"
    if field_type.kind == "string":
        result["maxLength"] = field_type.length
    return result


def _sql_type(field_type: SpecFieldType) -> str:
    return {
        "string": f"VARCHAR({field_type.length})",
        "integer": "INT",
        "bigint": "BIGINT",
        "decimal": f"DECIMAL({field_type.precision},{field_type.scale})",
        "boolean": "BOOLEAN",
        "date": "DATE",
        "datetime": "DATETIME(6)",
        "json": "JSON",
    }[field_type.kind]


def _ts_type(field_type: SpecFieldType) -> str:
    return {
        "string": "string",
        "integer": "number",
        "bigint": "number",
        "decimal": "number",
        "boolean": "boolean",
        "date": "string",
        "datetime": "string",
        "json": "Json",
    }[field_type.kind]


def _ts_identifier(value: str) -> str:
    # Component ids may contain the stable-id separator '-'; generated source
    # uses a conservative identifier independent of user text.
    return re.sub(r"[^A-Za-z0-9_]", "_", value)


def _sql_literal(value: str | int | float | bool) -> str:
    if isinstance(value, bool):
        return "1" if value else "0"
    if isinstance(value, (int, float)):
        return str(value)
    return "'" + value.replace("'", "''") + "'"


def _canonical(value: Any) -> str:
    return json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":"), indent=2) + "\n"
